%%{init: {'theme':'neutral'}}%%
classDiagram
    	
	class Investigation {
		Identifier, Title
	}
	class Study{
		Location, Timing, Design
	}
	class ObservationUnit{
		Type, Coordinates
	}
	class ObservedVariable{
		Trait, Method, Scale
	}
	class Publication{
		DOI
	}
	class Person{
		Name, Contact, Affiliation
	}
	class Factor{
		Type
	}
	class Event{
		Type, Description
	}
	class BiologicalMaterial{
		Organism, Source
	}
	class Sample{
		Collection, Anatomy, Development Stage
	}
	
    DataFile "0..n" --> "0..n" ObservationUnit
    DataFile "0..n" --> "0..n" Sample
    DataFile "1..n" --> "1..n" ObservedVariable
    EnvironmentParameter "1" --> "1" ParameterValue
    Event "1" --> "1..n" EventDate
    Factor "1" --> "2..n" FactorValue
    Investigation "1" --> "0..n" Person
    Investigation "1" --> "0..n" Publication
    Investigation "1" --> "1..n" Study
    ObservationUnit "0..n" --> "0..n" Event
    ObservationUnit "1" --> "0..n" Sample
    ObservationUnit "1..n" --> "0..n" FactorValue
    ObservationUnit "1..n" --> "1..n" BiologicalMaterial
    Study "0..n" --> "0..n" Person
    Study "1" --> "0..n" EnvironmentParameter
    Study "1" --> "0..n" Event
    Study "1" --> "0..n" Factor
    Study "1" --> "0..n" ObservationUnit
    Study "1" --> "1..n" DataFile
    Study "1" --> "1..n" ObservationUnit
    Study "1..n" --> "1..n" BiologicalMaterial
    Study "1..n" --> "1..n" ObservedVariable

    style Investigation fill:orange
    style Study fill:orange
    style ObservedVariable fill:orange
    style BiologicalMaterial fill:lightgreen
    style DataFile fill:lightyellow
